### ISSUE TITLE
Website is down? 

### ISSUE THREAD

**Issue by LifeIsStrange** [tomaarsen/Inflex#4]
:)

**Comment by tomaarsen** [comment]
Oh, was it? Hmmm. I'm struggling to find issues in my logs.

Did you mean e.g. https://www.tomaarsen.com/projects/inflex/try (my website where the Inflex performance is shown), or https://tomaarsen.github.io/Inflex/ with the Inflex documentation?

They both appear to be online for me, but maybe you can check whether it is still down for you?
Thanks for notifying me about this!

**Comment by LifeIsStrange** [comment]
I meant this url https://www.tomaarsen.com/projects/inflex/performance, its working correctly now :) Very interesting project BTW, the ability to specify a given inflexion for a given word and a given POS tag is something I have always desired!
I'm very suprised you are able to get this kind of accuracy!

**Comment by LifeIsStrange** [comment]
Edit: In fact the performance and the try link do not load on my smartphone (android, kiwi browser a chromium derivative)
But https://tomaarsen.github.io/Inflex/ works on my phone! 
Well it's a minor issue then since it works on the desktop

**Comment by tomaarsen** [comment]
They don't load at all? The website wasn't specifically designed for mobile, but mobile is "supposed" to work. On my android, both pages load, and the `try` page works. The `performance` page grows downwards endlessly for some reason.

**Comment by LifeIsStrange** [comment]
Yeh they don't load at all on kiwi browser
